name: itslars
favicon: null
layout_spectrum: 0.6105342884548008
typography_spectrum: 0.771161352051422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.978689975105226
  lightness: 0.8751521348021924
  saturation: 0.995292626786977
  rhythmicContrast: 0.22993345954455435
purpose: []
