typography_spectrum: 0.771161352051422
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: itslars
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: It's Lars!
description: Portfolio
purpose: []
